### ISSUE TITLE
Create generic challenge scene

### ISSUE THREAD

**Issue by davcri** [YouAreUto/YouAreUto#1]

**Comment by mp950** [comment]
Some issues I have noticed:
- On start: Tagline doesn't show (solved)
- On start: Logo overlaps with challenges before dissolving (solved) 
- EXIT button doesn't work (solved)
- CHALLENGE SELECTION button doesn't bring to the challenge selection screen (partially solved. Now it goes to the challenge selection screen but it shows the logo and then the challenge selection instead of transitioning directly to the challenge selection)
During the game:
- Uto doesn't move fluid (solved)
- QUIT button shows the logo and then challenge selection instead of transitioning directly to challenge selection (not solved)

- NEXT CHALLENGE button quits the app (solved)

- Challenge 3: rain audio is too low
